"""add cascade delete to session muscle groups

Revision ID: 3454d89f1359
Revises: 589acd11efdd
Create Date: 2026-09-18 09:28:29.099766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3454d89f1359'
down_revision: Union[str, Sequence[str], None] = '589acd11efdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workout_sessions_muscle_groups_workout_session_id_fkey'), 'workout_sessions_muscle_groups', type_='foreignkey')
    op.create_foreign_key(None, 'workout_sessions_muscle_groups', 'workout_sessions', ['workout_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sessions_muscle_groups', type_='foreignkey')
    op.create_foreign_key(op.f('workout_sessions_muscle_groups_workout_session_id_fkey'), 'workout_sessions_muscle_groups', 'workout_sessions', ['workout_session_id'], ['id'])
    # ### end Alembic commands ###
