"""add unique constraint to exercise name

Revision ID: 589acd11efdd
Revises: 6ff3a465ffa4
Create Date: 2026-09-13 20:09:33.047418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589acd11efdd'
down_revision: Union[str, Sequence[str], None] = '6ff3a465ffa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exercises', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='unique')
    # ### end Alembic commands ###
