"""add cascade delete to sets

Revision ID: da7ce36ba0a6
Revises: 3454d89f1359
Create Date: 2026-09-18 10:28:59.145122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7ce36ba0a6'
down_revision: Union[str, Sequence[str], None] = '3454d89f1359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sets_workout_exercise_id_fkey'), 'sets', type_='foreignkey')
    op.create_foreign_key(None, 'sets', 'workout_exercises', ['workout_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.create_foreign_key(op.f('sets_workout_exercise_id_fkey'), 'sets', 'workout_exercises', ['workout_exercise_id'], ['id'])
    # ### end Alembic commands ###
